/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorldsWorldIdRouteRouteImport } from './routes/worlds/$worldId/route'
import { Route as WorldsWorldIdIndexRouteImport } from './routes/worlds/$worldId/index'
import { Route as WorldsWorldIdArticlesArticleIdRouteImport } from './routes/worlds/$worldId/articles/$articleId'
import { Route as WorldsWorldIdCharactersArticleIdRouteImport } from './routes/worlds/$worldId/characters/$articleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldsWorldIdRouteRoute = WorldsWorldIdRouteRouteImport.update({
  id: '/worlds/$worldId',
  path: '/worlds/$worldId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldsWorldIdIndexRoute = WorldsWorldIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorldsWorldIdRouteRoute,
} as any)
const WorldsWorldIdArticlesArticleIdRoute =
  WorldsWorldIdArticlesArticleIdRouteImport.update({
    id: '/articles/$articleId',
    path: '/articles/$articleId',
    getParentRoute: () => WorldsWorldIdRouteRoute,
  } as any)
const WorldsWorldIdCharactersArticleIdRoute =
  WorldsWorldIdCharactersArticleIdRouteImport.update({
    id: '/characters/$articleId',
    path: '/characters/$articleId',
    getParentRoute: () => WorldsWorldIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/worlds/$worldId': typeof WorldsWorldIdRouteRouteWithChildren
  '/worlds/$worldId/': typeof WorldsWorldIdIndexRoute
  '/worlds/$worldId/articles/$articleId': typeof WorldsWorldIdArticlesArticleIdRoute
  '/worlds/$worldId/characters/$articleId': typeof WorldsWorldIdCharactersArticleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/worlds/$worldId': typeof WorldsWorldIdIndexRoute
  '/worlds/$worldId/articles/$articleId': typeof WorldsWorldIdArticlesArticleIdRoute
  '/worlds/$worldId/characters/$articleId': typeof WorldsWorldIdCharactersArticleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/worlds/$worldId': typeof WorldsWorldIdRouteRouteWithChildren
  '/worlds/$worldId/': typeof WorldsWorldIdIndexRoute
  '/worlds/$worldId/articles/$articleId': typeof WorldsWorldIdArticlesArticleIdRoute
  '/worlds/$worldId/characters/$articleId': typeof WorldsWorldIdCharactersArticleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/worlds/$worldId'
    | '/worlds/$worldId/'
    | '/worlds/$worldId/articles/$articleId'
    | '/worlds/$worldId/characters/$articleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/worlds/$worldId'
    | '/worlds/$worldId/articles/$articleId'
    | '/worlds/$worldId/characters/$articleId'
  id:
    | '__root__'
    | '/'
    | '/worlds/$worldId'
    | '/worlds/$worldId/'
    | '/worlds/$worldId/articles/$articleId'
    | '/worlds/$worldId/characters/$articleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorldsWorldIdRouteRoute: typeof WorldsWorldIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worlds/$worldId': {
      id: '/worlds/$worldId'
      path: '/worlds/$worldId'
      fullPath: '/worlds/$worldId'
      preLoaderRoute: typeof WorldsWorldIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worlds/$worldId/': {
      id: '/worlds/$worldId/'
      path: '/'
      fullPath: '/worlds/$worldId/'
      preLoaderRoute: typeof WorldsWorldIdIndexRouteImport
      parentRoute: typeof WorldsWorldIdRouteRoute
    }
    '/worlds/$worldId/articles/$articleId': {
      id: '/worlds/$worldId/articles/$articleId'
      path: '/articles/$articleId'
      fullPath: '/worlds/$worldId/articles/$articleId'
      preLoaderRoute: typeof WorldsWorldIdArticlesArticleIdRouteImport
      parentRoute: typeof WorldsWorldIdRouteRoute
    }
    '/worlds/$worldId/characters/$articleId': {
      id: '/worlds/$worldId/characters/$articleId'
      path: '/characters/$articleId'
      fullPath: '/worlds/$worldId/characters/$articleId'
      preLoaderRoute: typeof WorldsWorldIdCharactersArticleIdRouteImport
      parentRoute: typeof WorldsWorldIdRouteRoute
    }
  }
}

interface WorldsWorldIdRouteRouteChildren {
  WorldsWorldIdIndexRoute: typeof WorldsWorldIdIndexRoute
  WorldsWorldIdArticlesArticleIdRoute: typeof WorldsWorldIdArticlesArticleIdRoute
  WorldsWorldIdCharactersArticleIdRoute: typeof WorldsWorldIdCharactersArticleIdRoute
}

const WorldsWorldIdRouteRouteChildren: WorldsWorldIdRouteRouteChildren = {
  WorldsWorldIdIndexRoute: WorldsWorldIdIndexRoute,
  WorldsWorldIdArticlesArticleIdRoute: WorldsWorldIdArticlesArticleIdRoute,
  WorldsWorldIdCharactersArticleIdRoute: WorldsWorldIdCharactersArticleIdRoute,
}

const WorldsWorldIdRouteRouteWithChildren =
  WorldsWorldIdRouteRoute._addFileChildren(WorldsWorldIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorldsWorldIdRouteRoute: WorldsWorldIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
